#!/usr/bin/env python3
# Copyright (c) 2026 The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit.
"""Freeze Code Quantum runtime contract constants in shared CQ params.

This is a functional-layer parity guard that catches unintentional drift in the
native Code Quantum registry and budget profile while the broader integration
(address/RPC plumbing and full vector harness) is still being migrated.
"""

from pathlib import Path
import re

from test_framework.test_framework import BitcoinTestFramework


class CodeQuantumRuntimeContractTest(BitcoinTestFramework):
    def set_test_params(self):
        self.num_nodes = 0

    def setup_network(self):
        pass

    def run_test(self):
        srcdir = Path(self.config["environment"]["SRCDIR"])
        params = srcdir / "src" / "script" / "code_quantum_params.h"
        interpreter = srcdir / "src" / "script" / "interpreter.cpp"
        chainparams_kernel = srcdir / "src" / "kernel" / "chainparams.cpp"
        top_cmake = srcdir / "CMakeLists.txt"
        params_text = params.read_text(encoding="utf8")
        text = interpreter.read_text(encoding="utf8")
        chainparams_kernel_text = chainparams_kernel.read_text(encoding="utf8")
        top_cmake_text = top_cmake.read_text(encoding="utf8")

        self.log.info("Checking canonical Code Quantum budget constants")
        self.assert_match(params_text, r"MAX_WRAPPED_SIG_SIZE\{\s*73\s*\}", "MAX_WRAPPED_SIG_SIZE must remain 73")
        self.assert_match(params_text, r"MAX_ENVELOPE_SIZE\{\s*79\s*\}", "MAX_ENVELOPE_SIZE must remain 79")

        self.log.info("Checking canonical Code Quantum mode and algorithm IDs")
        self.assert_match(params_text, r"MODE_V1_WRAPPED_ECDSA\{\s*0\s*\}", "MODE_V1_WRAPPED_ECDSA must remain 0")
        self.assert_match(params_text, r"MODE_V1_RESERVED_EXTENSION_START\{\s*1\s*\}", "MODE_V1_RESERVED_EXTENSION_START must remain 1")
        self.assert_match(params_text, r"ALGORITHM_V1_WRAPPED_ECDSA_DER\{\s*0\s*\}", "ALGORITHM_V1_WRAPPED_ECDSA_DER must remain 0")
        self.assert_match(params_text, r"ALGORITHM_V1_SHA3_256T\{\s*1\s*\}", "ALGORITHM_V1_SHA3_256T must remain 1")
        self.assert_match(params_text, r"ALGORITHM_V1_ML_DSA_65\{\s*2\s*\}", "ALGORITHM_V1_ML_DSA_65 must remain 2")

        self.log.info("Checking active/known algorithm registry contract")
        self.assert_match(
            params_text,
            r"MODE_V1_KNOWN_ALGORITHMS\{\s*ALGORITHM_V1_WRAPPED_ECDSA_DER\s*,\s*ALGORITHM_V1_SHA3_256T\s*,\s*ALGORITHM_V1_ML_DSA_65\s*,\s*\};",
            "Known algorithm registry must include legacy + SHA3-256t + ML-DSA-65 IDs",
        )
        self.assert_match(
            params_text,
            r"MODE_V1_ACTIVE_ALGORITHMS\{\s*ALGORITHM_V1_WRAPPED_ECDSA_DER\s*,\s*ALGORITHM_V1_SHA3_256T\s*,\s*\};",
            "Active algorithm registry must include legacy + SHA3-256t IDs",
        )
        self.assert_match(
            params_text,
            r"ML_DSA_65_RUNTIME_ENABLED\{\s*false\s*\}",
            "ML_DSA_65_RUNTIME_ENABLED must remain false in emergency safe mode",
        )

        self.log.info("Checking interpreter aliases to canonical constants")
        self.assert_match(text, r"CODE_QUANTUM_MODE_V1_WRAPPED_ECDSA\s*=\s*codequantum::MODE_V1_WRAPPED_ECDSA", "Missing wrapped mode alias to shared params")
        self.assert_match(text, r"CODE_QUANTUM_ALGORITHM_V1_SHA3_256T\s*=\s*codequantum::ALGORITHM_V1_SHA3_256T", "Missing SHA3-256t alias to shared params")
        self.assert_match(text, r"CODE_QUANTUM_ALGORITHM_V1_ML_DSA_65\s*=\s*codequantum::ALGORITHM_V1_ML_DSA_65", "Missing ML-DSA-65 alias to shared params")
        self.assert_match(text, r"CODE_QUANTUM_ML_DSA_65_RUNTIME_ENABLED\s*=\s*codequantum::ML_DSA_65_RUNTIME_ENABLED", "Missing ML-DSA-65 runtime gate alias to shared params")
        self.assert_match(text, r"CODE_QUANTUM_MODE_V1_ACTIVE_ALGORITHMS\s*=\s*codequantum::MODE_V1_ACTIVE_ALGORITHMS", "Missing active algorithm alias to shared params")

        self.log.info("Checking SHA3-256t helper and dispatch hook presence")
        self.assert_match(text, r"static uint256 HashSHA3_256t\(const uint256& input\)", "Missing SHA3-256t helper")
        self.assert_match(text, r"if \(algorithm == CODE_QUANTUM_ALGORITHM_V1_WRAPPED_ECDSA_DER\)", "Missing legacy dispatch branch")
        self.assert_match(text, r"if \(algorithm == CODE_QUANTUM_ALGORITHM_V1_ML_DSA_65\)", "Missing ML-DSA-65 dispatch branch")
        self.assert_match(text, r"if \(!CODE_QUANTUM_ML_DSA_65_RUNTIME_ENABLED\)", "Missing ML-DSA-65 runtime gate check")
        self.assert_match(text, r"codequantum::VerifyMLDSA65Signature\(wrapped_sig, vchPubKey, scriptCode\)", "Missing ML-DSA-65 backend verify hook call")
        self.assert_match(text, r"if \(algorithm != CODE_QUANTUM_ALGORITHM_V1_SHA3_256T\)", "Missing SHA3-256t dispatch guard")
        self.assert_match(text, r"const uint256 sha3_sighash = HashSHA3_256t\(legacy_sighash\);", "Missing SHA3-256t sighash transform")

        self.log.info("Checking ML-DSA-65 placeholder backend input contract")
        mldsa_backend = (srcdir / "src" / "script" / "code_quantum_mldsa.cpp").read_text(encoding="utf8")
        mldsa_backend_impl = (srcdir / "src" / "script" / "code_quantum_mldsa_backend.cpp").read_text(encoding="utf8")
        mldsa_backend_provider_h = (srcdir / "src" / "script" / "code_quantum_mldsa_backend_provider.h").read_text(encoding="utf8")
        mldsa_backend_provider = (srcdir / "src" / "script" / "code_quantum_mldsa_backend_provider.cpp").read_text(encoding="utf8")
        mldsa_backend_native = (srcdir / "src" / "script" / "code_quantum_mldsa_backend_native.cpp").read_text(encoding="utf8")
        mldsa_backend_native_h = (srcdir / "src" / "script" / "code_quantum_mldsa_backend_native.h").read_text(encoding="utf8")
        sign_cpp = (srcdir / "src" / "script" / "sign.cpp").read_text(encoding="utf8")
        signingprovider_h = (srcdir / "src" / "script" / "signingprovider.h").read_text(encoding="utf8")
        signingprovider_cpp = (srcdir / "src" / "script" / "signingprovider.cpp").read_text(encoding="utf8")
        wallet_h = (srcdir / "src" / "wallet" / "wallet.h").read_text(encoding="utf8")
        wallet_init = (srcdir / "src" / "wallet" / "init.cpp").read_text(encoding="utf8")
        wallet_cpp = (srcdir / "src" / "wallet" / "wallet.cpp").read_text(encoding="utf8")
        self.assert_match(mldsa_backend, r"bool ParseMLDSA65WrappedSignature\(const std::vector<unsigned char>& wrapped_sig,", "Missing wrapped-signature parse API")
        self.assert_match(mldsa_backend, r"bool ParseMLDSA65WrappedSignatureDetailed\(const std::vector<unsigned char>& wrapped_sig,", "Missing wrapped-signature detailed parse API")
        self.assert_match(mldsa_backend, r"bool ParseMLDSA65PubKey\(const std::vector<unsigned char>& vchPubKey,", "Missing pubkey parse API")
        self.assert_match(mldsa_backend, r"bool ParseMLDSA65PubKeyDetailed\(const std::vector<unsigned char>& vchPubKey,", "Missing pubkey detailed parse API")
        self.assert_match(mldsa_backend, r"bool VerifyMLDSA65SignatureDetailed\(const std::vector<unsigned char>& wrapped_sig,", "Missing detailed verify API")
        self.assert_match(mldsa_backend, r"bool IsStructurallyValidMLDSA65WrappedSignature\(const std::vector<unsigned char>& wrapped_sig\)", "Missing wrapped-signature parser helper")
        self.assert_match(mldsa_backend, r"bool IsStructurallyValidMLDSA65PubKey\(const std::vector<unsigned char>& vchPubKey\)", "Missing pubkey parser helper")
        self.assert_match(mldsa_backend, r"wrapped_sig\.empty\(\)\s*\|\|\s*wrapped_sig\.size\(\)\s*>\s*MAX_WRAPPED_SIG_SIZE", "Missing wrapped signature shape guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(wrapped_sig\.size\(\)\s*<\s*9\)", "Missing wrapped signature minimum-size guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(wrapped_sig\[0\]\s*!=\s*0x30\)", "Missing DER sequence tag guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"const size_t der_sig_size\{static_cast<size_t>\(wrapped_sig\[1\]\) \+ 2\};", "Missing DER length extraction in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(der_sig_size \+ 1 != wrapped_sig\.size\(\)\)", "Missing DER length consistency guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(wrapped_sig\[2\] != 0x02\)", "Missing DER R-integer tag guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"const size_t r_len\{static_cast<size_t>\(wrapped_sig\[3\]\)\};", "Missing DER R-length extraction in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(wrapped_sig\[s_tag_offset\] != 0x02\)", "Missing DER S-integer tag guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(s_offset \+ s_len != der_sig_size\)", "Missing DER R/S envelope boundary guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"constexpr std::array<unsigned char, 32> SECP256K1_HALF_ORDER", "Missing secp256k1 half-order low-S constant")
        self.assert_match(mldsa_backend, r"SetWrappedSigParseError\(out_error, MLDSA65WrappedSigParseError::BAD_SEQUENCE_TAG\);", "Missing BAD_SEQUENCE_TAG parse reason mapping")
        self.assert_match(mldsa_backend, r"SetWrappedSigParseError\(out_error, MLDSA65WrappedSigParseError::NON_MINIMAL_R\);", "Missing NON_MINIMAL_R parse reason mapping")
        self.assert_match(mldsa_backend, r"SetWrappedSigParseError\(out_error, MLDSA65WrappedSigParseError::HIGH_S\);", "Missing HIGH_S parse reason mapping")
        self.assert_match(mldsa_backend, r"SetWrappedSigParseError\(out_error, MLDSA65WrappedSigParseError::ZERO_HASHTYPE\);", "Missing ZERO_HASHTYPE parse reason mapping")
        self.assert_match(mldsa_backend, r"SetWrappedSigParseError\(out_error, MLDSA65WrappedSigParseError::OK\);", "Missing OK parse reason mapping")
        self.assert_match(mldsa_backend, r"SetPubKeyParseError\(out_error, MLDSA65PubKeyParseError::EMPTY\);", "Missing pubkey EMPTY parse reason mapping")
        self.assert_match(mldsa_backend, r"SetPubKeyParseError\(out_error, MLDSA65PubKeyParseError::OVERSIZE\);", "Missing pubkey OVERSIZE parse reason mapping")
        self.assert_match(mldsa_backend, r"SetPubKeyParseError\(out_error, MLDSA65PubKeyParseError::INVALID_FORMAT\);", "Missing pubkey INVALID_FORMAT parse reason mapping")
        self.assert_match(mldsa_backend, r"SetPubKeyParseError\(out_error, MLDSA65PubKeyParseError::OK\);", "Missing pubkey OK parse reason mapping")
        self.assert_match(mldsa_backend, r"SetVerifyError\(out_error, MLDSA65VerifyError::WRAPPED_SIG_INVALID\);", "Missing verify WRAPPED_SIG_INVALID reason mapping")
        self.assert_match(mldsa_backend, r"SetVerifyError\(out_error, MLDSA65VerifyError::PUBKEY_INVALID\);", "Missing verify PUBKEY_INVALID reason mapping")
        self.assert_match(mldsa_backend, r"SetVerifyError\(out_error, MLDSA65VerifyError::EMPTY_SCRIPT_CODE\);", "Missing verify EMPTY_SCRIPT_CODE reason mapping")
        self.assert_match(mldsa_backend, r"SetVerifyError\(out_error, MLDSA65VerifyError::BACKEND_REJECTED\);", "Missing verify BACKEND_REJECTED reason mapping")
        self.assert_match(mldsa_backend, r"SetVerifyError\(out_error, MLDSA65VerifyError::BACKEND_NOT_IMPLEMENTED\);", "Missing verify BACKEND_NOT_IMPLEMENTED reason mapping")
        self.assert_match(mldsa_backend, r"if \(g_mldsa65_backend_verifier != nullptr && g_mldsa65_backend_verifier\(wrapped_sig, vchPubKey, scriptCode\)\)", "Missing backend hook success gate")
        self.assert_match(mldsa_backend, r"MLDSA65BackendResultVerifier g_mldsa65_backend_result_verifier\{nullptr\};", "Missing result-aware backend hook state")
        self.assert_match(mldsa_backend, r"if \(g_mldsa65_backend_result_verifier != nullptr\)", "Missing result-aware backend hook gate")
        self.assert_match(mldsa_backend, r"hook_result == MLDSA65BackendAdapterResult::UNAVAILABLE", "Missing unavailable hook fallthrough branch")
        self.assert_match(mldsa_backend, r"SetMLDSA65BackendResultVerifierForTesting\(MLDSA65BackendResultVerifier verifier\)", "Missing result-aware backend hook setter")
        self.assert_match(mldsa_backend, r"ResetMLDSA65BackendResultVerifierForTesting\(\)", "Missing result-aware backend hook resetter")
        self.assert_match(mldsa_backend, r"return VerifyMLDSA65BackendAdapterResultImpl\(wrapped_sig, vchPubKey, scriptCode\);", "Backend adapter must delegate to extracted backend module")
        self.assert_match(mldsa_backend_impl, r"bool VerifyMLDSA65BackendAdapterImpl\(const std::vector<unsigned char>& wrapped_sig,", "Missing extracted ML-DSA backend module entrypoint")
        self.assert_match(mldsa_backend_impl, r"MLDSA65BackendAdapterResult VerifyMLDSA65BackendAdapterResultImpl\(const std::vector<unsigned char>& wrapped_sig,", "Missing extracted ML-DSA backend result entrypoint")
        self.assert_match(mldsa_backend_impl, r"(codequantum::)?MLDSA65BackendAdapterResult VerifyMLDSA65WithNativeBackend\(const std::vector<unsigned char>&", "Missing native backend shim entrypoint")
        self.assert_match(mldsa_backend_impl, r"if \(!codequantum::MLDSA65NativeBackendAvailable\(\)\)", "Missing native backend availability gate")
        self.assert_match(mldsa_backend_impl, r"return codequantum::VerifyMLDSA65NativeBackend\(wrapped_sig, vchPubKey, scriptCode\);", "Missing native backend provider dispatch")
        self.assert_match(mldsa_backend_impl, r"const MLDSA65BackendAdapterResult native_result\s*=\s*VerifyMLDSA65WithNativeBackend\(wrapped_sig, vchPubKey, scriptCode\);", "Missing native backend invocation in adapter")
        self.assert_match(mldsa_backend_impl, r"if \(native_result != MLDSA65BackendAdapterResult::UNAVAILABLE\)", "Missing native backend short-circuit guard")
        self.assert_match(mldsa_backend_impl, r"const MLDSA65BackendAdapterResult native_result\s*=\s*VerifyMLDSA65WithNativeBackend\(wrapped_sig, vchPubKey, scriptCode\);\s*\n\s*if \(native_result != MLDSA65BackendAdapterResult::UNAVAILABLE\)\s*\{\s*\n\s*return native_result;\s*\n\s*\}\s*\n\s*// Temporary deterministic fallback contract until native backend lands\.\s*\n\s*for \(const BackendVector& vector : KNOWN_GOOD_BACKEND_VECTORS\)", "Missing native-dispatch fallback ordering contract (UNAVAILABLE -> deterministic adapter vectors)")
        self.assert_match(mldsa_backend_provider, r"bool MLDSA65NativeBackendAvailable\(\)", "Missing provider availability API")
        self.assert_match(mldsa_backend_provider, r"#if defined\(ENABLE_MLDSA65_NATIVE_BACKEND\)", "Missing provider compile-time backend gate")
        self.assert_match(mldsa_backend_provider, r"MLDSA65NativeBackendBinding g_mldsa65_native_backend_binding\{nullptr, nullptr\};", "Missing provider-native binding storage")
        self.assert_match(mldsa_backend_provider, r"bool g_mldsa65_native_backend_initialized\{false\};", "Missing provider-native lazy init guard")
        self.assert_match(mldsa_backend_provider, r"bool MLDSA65NativeBackendBindingSupported\(const MLDSA65NativeBackendBinding& binding\)", "Missing provider-native binding-shape compatibility helper")
        self.assert_match(mldsa_backend_provider, r"return binding\.verify != nullptr \|\| binding\.sign != nullptr;", "Missing provider-native verify-or-sign binding policy")
        self.assert_match(mldsa_backend_provider, r"MLDSA65NativeBackendBinding GetMLDSA65NativeBackendImplementationBindingImpl\(\)", "Missing native backend implementation-binding seam entrypoint")
        self.assert_match(mldsa_backend_provider, r"if \(g_mldsa65_native_backend_implementation_binding_for_testing_set\)", "Missing implementation-binding testing override gate")
        self.assert_match(mldsa_backend_provider, r"return g_mldsa65_native_backend_implementation_binding_for_testing;", "Missing implementation-binding testing override dispatch")
        self.assert_match(mldsa_backend_provider, r"return \{nullptr, nullptr\};", "Missing native backend implementation-binding placeholder contract")
        self.assert_match(mldsa_backend_provider, r"void EnsureMLDSA65NativeBackendBindingInitialized\(\)", "Missing provider-native lazy init routine")
        self.assert_match(mldsa_backend_provider, r"if \(g_mldsa65_native_backend_initialized\)\s*\{\s*\n\s*return;\s*\n\s*\}", "Missing provider-native lazy-init idempotence early-return guard")
        self.assert_match(mldsa_backend_provider, r"const MLDSA65NativeBackendBinding implementation_binding = GetMLDSA65NativeBackendImplementationBindingImpl\(\);", "Missing provider implementation-binding acquisition in lazy init")
        self.assert_match(mldsa_backend_provider, r"if \(MLDSA65NativeBackendBindingSupported\(implementation_binding\)\)\s*\{\s*\n\s*g_mldsa65_native_backend_binding = implementation_binding;(?:.|\n)*?\n\s*return;\s*\n\s*\}", "Missing provider implementation-binding precedence contract")
        self.assert_match(mldsa_backend_provider, r"const MLDSA65NativeBackendBinding default_binding = GetDefaultMLDSA65NativeBackendBinding\(\);", "Missing default native binding acquisition")
        self.assert_match(mldsa_backend_provider, r"if \(default_binding\.is_available != nullptr \|\| default_binding\.verify != nullptr \|\| default_binding\.sign != nullptr\)", "Missing default native binding non-empty guard")
        self.assert_match(mldsa_backend_provider, r"if \(MLDSA65NativeBackendBindingSupported\(default_binding\)\)", "Missing lazy-init half-binding rejection guard for default native binding")
        self.assert_match(mldsa_backend_provider, r"EnsureMLDSA65NativeBackendBindingInitialized\(\);", "Missing provider lazy init invocation")
        self.assert_match(mldsa_backend_provider, r"if \(!MLDSA65NativeBackendBindingSupported\(g_mldsa65_native_backend_binding\)\)", "Missing provider-native unsupported-binding availability guard")
        self.assert_match(mldsa_backend_provider, r"if \(g_mldsa65_native_backend_binding\.is_available != nullptr\)", "Missing provider explicit availability callback guard")
        self.assert_match(mldsa_backend_provider, r"return g_mldsa65_native_backend_binding\.verify != nullptr;", "Missing provider verify-pointer availability fallback")
        self.assert_match(mldsa_backend_provider, r"void SetMLDSA65NativeBackendImplementationBindingForTesting\(const MLDSA65NativeBackendBinding& binding\)", "Missing implementation-binding testing seam setter")
        self.assert_match(mldsa_backend_provider, r"void ResetMLDSA65NativeBackendImplementationBindingForTesting\(\)", "Missing implementation-binding testing seam resetter")
        self.assert_match(mldsa_backend_provider, r"return false;", "Missing provider default-disabled availability contract")
        self.assert_match(mldsa_backend_provider, r"MLDSA65BackendAdapterResult VerifyMLDSA65NativeBackend\(const std::vector<unsigned char>&\s+\w+,", "Missing provider verify API")
        self.assert_match(mldsa_backend_provider, r"const MLDSA65BackendAdapterResult normalized_result = NormalizeMLDSA65NativeBackendResult\(", "Missing provider native verifier dispatch normalization")
        self.assert_match(mldsa_backend_provider, r"g_mldsa65_native_backend_binding\.verify\(wrapped_sig, vchPubKey, scriptCode\)", "Missing provider native verifier callback invocation")
        self.assert_match(mldsa_backend_provider, r"void RegisterMLDSA65NativeBackendBinding\(const MLDSA65NativeBackendBinding& binding\)", "Missing provider production binding registration API")
        self.assert_match(mldsa_backend_provider, r"g_mldsa65_native_backend_initialized = true;", "Missing provider initialized latch update on register")
        self.assert_match(mldsa_backend_provider, r"g_mldsa65_native_backend_initialized = false;", "Missing provider initialized latch reset for unsupported register path")
        self.assert_match(mldsa_backend_provider, r"void ClearMLDSA65NativeBackendBinding\(\)", "Missing provider production binding clear API")
        self.assert_match(mldsa_backend_provider, r"g_mldsa65_native_backend_initialized = false;", "Missing provider initialized latch reset on clear")
        self.assert_match(mldsa_backend_provider, r"void SetMLDSA65NativeBackendVerifierForTesting\(MLDSA65NativeBackendVerifier verifier\)", "Missing provider native verifier setter")
        self.assert_match(mldsa_backend_provider, r"void ResetMLDSA65NativeBackendVerifierForTesting\(\)", "Missing provider native verifier resetter")
        self.assert_match(mldsa_backend_provider, r"MLDSA65NativeBackendSignResult SignMLDSA65NativeBackend\(const std::vector<unsigned char>&\s+\w+,", "Missing provider native signer API")
        self.assert_match(mldsa_backend_provider, r"MLDSA65NativeBackendSignResult NormalizeMLDSA65NativeBackendSignResult\(MLDSA65NativeBackendSignResult result\)", "Missing provider native signer result normalization")
        self.assert_match(mldsa_backend_provider_h, r"constexpr std::array<unsigned char, 18> MLDSA65_NATIVE_SIGN_PREHASH_DOMAIN_TAG\{", "Missing provider signer prehash domain-tag contract")
        self.assert_match(mldsa_backend_provider_h, r"const std::array<unsigned char, 32>& prehashed_sighash32", "Missing provider signer callback prehashed-sighash contract")
        self.assert_match(mldsa_backend_provider_h, r"std::array<unsigned char, 32> ComputeMLDSA65NativeSigningPrehash\(const CScript& scriptCode,", "Missing provider signer prehash helper declaration")
        self.assert_match(mldsa_backend_provider, r"std::array<unsigned char, 32> ComputeMLDSA65NativeSigningPrehash\(const CScript& scriptCode,", "Missing provider signer prehash helper definition")
        self.assert_match(mldsa_backend_provider, r"hasher\.Write\(MLDSA65_NATIVE_SIGN_PREHASH_DOMAIN_TAG\.data\(\), MLDSA65_NATIVE_SIGN_PREHASH_DOMAIN_TAG\.size\(\)\);", "Missing provider signer prehash domain-tag contribution")
        self.assert_match(mldsa_backend_provider, r"SignMLDSA65NativeBackend\(const std::vector<unsigned char>&[\s\S]*?out_wrapped_sig\.clear\(\);", "Missing deterministic signer output-clear contract before fallback paths")
        self.assert_match(mldsa_backend_provider, r"const std::array<unsigned char, 32> prehashed_sighash32\s*=\s*ComputeMLDSA65NativeSigningPrehash\(scriptCode, sighash_type\);", "Missing provider signer prehash helper invocation")
        self.assert_match(mldsa_backend_provider, r"g_mldsa65_native_backend_binding\.sign\(key_material, prehashed_sighash32, sighash_type, out_wrapped_sig\)", "Missing provider native signer callback invocation")
        self.assert_match(mldsa_backend_provider, r"void SetMLDSA65NativeBackendSignerForTesting\(MLDSA65NativeBackendSigner signer\)", "Missing provider native signer setter")
        self.assert_match(mldsa_backend_provider, r"void ResetMLDSA65NativeBackendSignerForTesting\(\)", "Missing provider native signer resetter")
        self.assert_match(mldsa_backend_provider, r"return MLDSA65BackendAdapterResult::UNAVAILABLE;", "Missing provider default unavailable contract")
        self.assert_match(mldsa_backend_native, r"MLDSA65NativeBackendBinding GetDefaultMLDSA65NativeBackendBinding\(\)", "Missing default native binding module entrypoint")
        self.assert_match(mldsa_backend_native, r"MLDSA65NativeBackendBindingFactory g_mldsa65_native_default_binding_factory\{nullptr\};", "Missing default native binding factory state")
        self.assert_match(mldsa_backend_native, r"if \(g_mldsa65_native_default_binding_factory != nullptr\)", "Missing default native binding factory override guard")
        self.assert_match(mldsa_backend_native, r"return g_mldsa65_native_default_binding_factory\(\);", "Missing default native binding factory dispatch")
        self.assert_match(mldsa_backend_native, r"void SetDefaultMLDSA65NativeBackendBindingFactoryForTesting\(MLDSA65NativeBackendBindingFactory factory\)", "Missing default native binding factory setter")
        self.assert_match(mldsa_backend_native, r"void ResetDefaultMLDSA65NativeBackendBindingFactoryForTesting\(\)", "Missing default native binding factory resetter")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendScaffoldEnabled\(\)", "Missing external-backend scaffold introspection API")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendHeaderDetected\(\)", "Missing external-backend header introspection API")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendBridgeReady\(\)", "Missing external-backend bridge readiness API")
        self.assert_match(mldsa_backend_native, r"MLDSA65BackendAdapterResult VerifyMLDSA65ExternalBackendAdapter\(const std::vector<unsigned char>& wrapped_sig,", "Missing external-backend adapter verify API")
        self.assert_match(signingprovider_h, r"virtual bool GetCScriptByHash256\(const uint256& scriptid256, CScript& script\) const", "Missing signing provider hash256 script lookup API")
        self.assert_match(signingprovider_h, r"std::map<uint256, CScript> scripts_hash256;", "Missing flat signing provider hash256 script map")
        self.assert_match(signingprovider_cpp, r"mapScriptsHash256\[Hash\(redeemScript\)\] = redeemScript;", "Missing fillable provider hash256 script indexing")
        self.assert_match(sign_cpp, r"case TxoutType::SCRIPTHASH32:\s*\{\s*uint256 h256\{vSolutions\[0\]\};", "Missing SCRIPTHASH32 signing dispatch branch")
        self.assert_match(sign_cpp, r"provider\.GetCScriptByHash256\(h256, scriptRet\)", "Missing SCRIPTHASH32 hash256 redeem-script lookup")
        self.assert_match(sign_cpp, r"whichType == TxoutType::SCRIPTHASH \|\| whichType == TxoutType::SCRIPTHASH32", "Missing SCRIPTHASH32 recursive signing path")
        self.assert_match(wallet_h, r"DEFAULT_ENABLE_CODE_QUANTUM_SIGNING\s*=\s*false", "Missing wallet default gate for Code Quantum signing")
        self.assert_match(wallet_init, r"-enablecodequantumsigning", "Missing wallet CLI feature gate for Code Quantum signing")
        self.assert_match(wallet_cpp, r"Code Quantum input signing is disabled \(-enablecodequantumsigning=1 to enable\)", "Missing wallet Code Quantum signing gate error mapping")
        self.assert_match(wallet_cpp, r"Code Quantum signer backend unavailable \(runtime is verify-only\)", "Missing wallet Code Quantum signer-unavailable error mapping")
        self.assert_match(sign_cpp, r"Code Quantum signing failed \(malformed key material or unsupported mode\)", "Missing Code Quantum malformed-key/unsupported-mode signing error mapping")
        self.assert_match(mldsa_backend_native_h, r"struct MLDSA65ExternalBackendRequest", "Missing external-backend canonical request contract type")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint32_t MLDSA65_EXTERNAL_BACKEND_REQUEST_VERSION\{1\};", "Missing external-backend request version constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint32_t MLDSA65_EXTERNAL_BACKEND_CAPABILITY_PREHASHED_SIGHASH\{1U << 0\};", "Missing external-backend prehashed-sighash capability bit")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint32_t MLDSA65_EXTERNAL_BACKEND_CAPABILITY_DER_WRAPPED_SIGNATURE\{1U << 1\};", "Missing external-backend DER-wrapped-signature capability bit")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint32_t MLDSA65_EXTERNAL_BACKEND_CAPABILITIES_BASELINE\{", "Missing external-backend baseline capabilities bitmap")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint32_t MLDSA65_EXTERNAL_BACKEND_CAPABILITY_PROFILE_BASELINE_V1\{1\};", "Missing external-backend capability profile marker constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr std::array<unsigned char, 8> MLDSA65_EXTERNAL_BACKEND_REQUEST_MAGIC\{", "Missing external-backend request integrity magic constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint32_t MLDSA65_EXTERNAL_BACKEND_REQUEST_SHAPE_HASH\{0x434d3651U\};", "Missing external-backend request integrity shape-hash constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr std::array<unsigned char, 16> MLDSA65_EXTERNAL_BACKEND_INTERFACE_ID\{", "Missing external-backend interface ID constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr std::array<unsigned char, 13> MLDSA65_EXTERNAL_BACKEND_PREHASH_DOMAIN_TAG\{", "Missing external-backend prehash domain tag constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr std::array<unsigned char, 12> MLDSA65_EXTERNAL_BACKEND_REQUEST_DIGEST_DOMAIN_TAG\{", "Missing external-backend request digest domain tag constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint8_t MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_VERIFIED\{0\};", "Missing external-backend verified result-code constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint8_t MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_REJECTED\{1\};", "Missing external-backend rejected result-code constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr uint8_t MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_UNAVAILABLE\{2\};", "Missing external-backend unavailable result-code constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr size_t MLDSA65_EXTERNAL_BACKEND_MAX_WRAPPED_SIG_SIZE\{73\};", "Missing external-backend max wrapped-sig size constant")
        self.assert_match(mldsa_backend_native_h, r"constexpr size_t MLDSA65_EXTERNAL_BACKEND_MAX_PUBKEY_SIZE\{65\};", "Missing external-backend max pubkey size constant")
        self.assert_match(mldsa_backend_native_h, r"uint32_t request_version;", "Missing external-backend request version field")
        self.assert_match(mldsa_backend_native_h, r"uint32_t capability_flags;", "Missing external-backend capability flags field")
        self.assert_match(mldsa_backend_native_h, r"uint32_t capability_profile_id;", "Missing external-backend capability profile field")
        self.assert_match(mldsa_backend_native_h, r"std::array<unsigned char, 8> request_magic;", "Missing external-backend request integrity magic field")
        self.assert_match(mldsa_backend_native_h, r"uint32_t request_shape_hash;", "Missing external-backend request integrity shape-hash field")
        self.assert_match(mldsa_backend_native_h, r"std::array<unsigned char, 16> external_backend_interface_id;", "Missing external-backend interface ID field")
        self.assert_match(mldsa_backend_native_h, r"std::array<unsigned char, 13> prehash_domain_tag;", "Missing external-backend prehash domain tag field")
        self.assert_match(mldsa_backend_native_h, r"std::array<unsigned char, 32> prehashed_sighash32;", "Missing external-backend prehashed sighash field")
        self.assert_match(mldsa_backend_native_h, r"std::array<unsigned char, 32> request_content_digest32;", "Missing external-backend request content digest field")
        self.assert_match(mldsa_backend_native_h, r"using MLDSA65ExternalBackendRequestObserver = void \(\*\)\(const MLDSA65ExternalBackendRequest& request\);", "Missing external-backend request observer type")
        self.assert_match(mldsa_backend_native_h, r"using MLDSA65ExternalBackendResultCodeVerifier = uint8_t \(\*\)\(const MLDSA65ExternalBackendRequest& request\);", "Missing external-backend result-code verifier type")
        self.assert_match(mldsa_backend_native_h, r"std::array<unsigned char, 32> ComputeMLDSA65ExternalBackendRequestContentDigest\(const MLDSA65ExternalBackendRequest& request\);", "Missing external-backend request content digest helper declaration")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendRequestVersionSupported\(uint32_t request_version\)", "Missing external-backend request version compatibility helper")
        self.assert_match(mldsa_backend_native, r"return request_version == MLDSA65_EXTERNAL_BACKEND_REQUEST_VERSION;", "Missing external-backend request version compatibility policy")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendCapabilitiesSupported\(uint32_t capability_flags\)", "Missing external-backend capability compatibility helper")
        self.assert_match(mldsa_backend_native, r"const uint32_t unknown_flags = capability_flags & ~MLDSA65_EXTERNAL_BACKEND_CAPABILITIES_BASELINE;", "Missing external-backend unknown capability mask")
        self.assert_match(mldsa_backend_native, r"return unknown_flags == 0;", "Missing external-backend unknown capability rejection policy")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendCapabilityProfileSupported\(uint32_t capability_profile_id\)", "Missing external-backend capability-profile compatibility helper")
        self.assert_match(mldsa_backend_native, r"return capability_profile_id == MLDSA65_EXTERNAL_BACKEND_CAPABILITY_PROFILE_BASELINE_V1;", "Missing external-backend capability-profile compatibility policy")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendInterfaceIdSupported\(const std::array<unsigned char, 16>& interface_id\)", "Missing external-backend interface ID compatibility helper")
        self.assert_match(mldsa_backend_native, r"return interface_id == MLDSA65_EXTERNAL_BACKEND_INTERFACE_ID;", "Missing external-backend interface ID compatibility policy")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendResultCodeSupported\(uint8_t result_code\)", "Missing external-backend result-code compatibility helper")
        self.assert_match(mldsa_backend_native, r"result_code == MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_VERIFIED", "Missing external-backend verified result-code support policy")
        self.assert_match(mldsa_backend_native, r"result_code == MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_REJECTED", "Missing external-backend rejected result-code support policy")
        self.assert_match(mldsa_backend_native, r"result_code == MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_UNAVAILABLE", "Missing external-backend unavailable result-code support policy")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendRequestSizesSupported\(size_t wrapped_sig_size,", "Missing external-backend request-size compatibility helper")
        self.assert_match(mldsa_backend_native, r"if \(wrapped_sig_size == 0 \|\| wrapped_sig_size > MLDSA65_EXTERNAL_BACKEND_MAX_WRAPPED_SIG_SIZE\)", "Missing external-backend wrapped-signature size bounds policy")
        self.assert_match(mldsa_backend_native, r"if \(pubkey_size == 0 \|\| pubkey_size > MLDSA65_EXTERNAL_BACKEND_MAX_PUBKEY_SIZE\)", "Missing external-backend pubkey size bounds policy")
        self.assert_match(mldsa_backend_native, r"if \(der_sig_size == 0 \|\| der_sig_size \+ 1 != wrapped_sig_size\)", "Missing external-backend DER-size consistency policy")
        self.assert_match(mldsa_backend_native, r"if \(pubkey_payload_size \+ 1 != pubkey_size\)", "Missing external-backend pubkey-payload size consistency policy")
        self.assert_match(mldsa_backend_native, r"bool MLDSA65ExternalBackendRequestPointersSupported\(const MLDSA65ExternalBackendRequest& request\)", "Missing external-backend request-pointer compatibility helper")
        self.assert_match(mldsa_backend_native, r"if \(request\.wrapped_sig == nullptr \|\| request\.pubkey == nullptr \|\| request\.script_code == nullptr\)", "Missing external-backend null-pointer rejection policy")
        self.assert_match(mldsa_backend_native, r"if \(request\.script_code->empty\(\)\)", "Missing external-backend script pointer non-empty policy")
        self.assert_match(mldsa_backend_native, r"return MLDSA65ExternalBackendRequestSizesSupported\(", "Missing external-backend pointer helper size-policy linkage")
        self.assert_match(mldsa_backend_native, r"std::array<unsigned char, 32> ComputeMLDSA65ExternalBackendRequestContentDigest\(const MLDSA65ExternalBackendRequest& request\)", "Missing external-backend request content digest helper")
        self.assert_match(mldsa_backend_native, r"hasher\.Write\(MLDSA65_EXTERNAL_BACKEND_REQUEST_DIGEST_DOMAIN_TAG\.data\(\), MLDSA65_EXTERNAL_BACKEND_REQUEST_DIGEST_DOMAIN_TAG\.size\(\)\);", "Missing external-backend request digest domain-tag contribution")
        self.assert_match(mldsa_backend_native, r"request\.request_content_digest32 = ComputeMLDSA65ExternalBackendRequestContentDigest\(request\);", "Missing external-backend request content digest assignment")
        self.assert_match(mldsa_backend_native, r"MLDSA65BackendAdapterResult TranslateMLDSA65ExternalBackendResultCode\(uint8_t result_code\)", "Missing external-backend result-code translation helper")
        self.assert_match(mldsa_backend_native, r"if \(result_code == MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_VERIFIED\)", "Missing external-backend verified translation branch")
        self.assert_match(mldsa_backend_native, r"if \(result_code == MLDSA65_EXTERNAL_BACKEND_RESULT_CODE_REJECTED\)", "Missing external-backend rejected translation branch")
        self.assert_match(mldsa_backend_native, r"void SetMLDSA65ExternalBackendVerifierForTesting\(MLDSA65NativeBackendVerifier verifier\)", "Missing external-backend verifier bridge setter")
        self.assert_match(mldsa_backend_native, r"void ResetMLDSA65ExternalBackendVerifierForTesting\(\)", "Missing external-backend verifier bridge resetter")
        self.assert_match(mldsa_backend_native, r"void SetMLDSA65ExternalBackendRequestObserverForTesting\(MLDSA65ExternalBackendRequestObserver observer\)", "Missing external-backend request observer setter")
        self.assert_match(mldsa_backend_native, r"void ResetMLDSA65ExternalBackendRequestObserverForTesting\(\)", "Missing external-backend request observer resetter")
        self.assert_match(mldsa_backend_native, r"void SetMLDSA65ExternalBackendResultCodeVerifierForTesting\(MLDSA65ExternalBackendResultCodeVerifier verifier\)", "Missing external-backend result-code verifier setter")
        self.assert_match(mldsa_backend_native, r"void ResetMLDSA65ExternalBackendResultCodeVerifierForTesting\(\)", "Missing external-backend result-code verifier resetter")
        self.assert_match(mldsa_backend_native, r"#if defined\(ENABLE_MLDSA65_EXTERNAL_BACKEND_SCAFFOLD\)", "Missing external-backend scaffold compile-time guard")
        self.assert_match(mldsa_backend_native, r"#if defined\(HAVE_MLDSA65_EXTERNAL_BACKEND_HEADER\)", "Missing external-backend header-detected compile-time guard")
        self.assert_match(mldsa_backend_native, r"MLDSA65NativeBackendVerifier g_mldsa65_external_backend_verifier\{nullptr\};", "Missing external-backend verifier bridge state")
        self.assert_match(mldsa_backend_native, r"MLDSA65ExternalBackendResultCodeVerifier g_mldsa65_external_backend_result_code_verifier\{nullptr\};", "Missing external-backend result-code verifier bridge state")
        self.assert_match(mldsa_backend_native, r"void WriteUint32LE\(CSHA256& hasher, uint32_t value\)", "Missing external-backend uint32 little-endian serializer helper")
        self.assert_match(mldsa_backend_native, r"void WriteUint64LE\(CSHA256& hasher, uint64_t value\)", "Missing external-backend uint64 little-endian serializer helper")
        self.assert_match(mldsa_backend_native, r"if \(MLDSA65ExternalBackendScaffoldEnabled\(\) && MLDSA65ExternalBackendHeaderDetected\(\)\)", "Missing default-binding external bridge activation guard")
        self.assert_match(mldsa_backend_native, r"return \{ExternalBackendAvailable, ExternalBackendVerify\};", "Missing default-binding external bridge callback wiring")
        self.assert_match(mldsa_backend_native, r"#if defined\(HAVE_MLDSA65_EXTERNAL_BACKEND_VERIFY_API\) && defined\(HAVE_MLDSA65_EXTERNAL_BACKEND_VERIFY_LINK\)", "Missing real external verify API+link bridge-ready gate")
        self.assert_match(mldsa_backend_native, r"return true;", "Missing bridge-ready fast-path for real external verify API")
        self.assert_match(mldsa_backend_native, r"return g_mldsa65_external_backend_verifier != nullptr;", "Missing external-backend fallback bridge readiness condition")
        self.assert_match(mldsa_backend_native, r"if \(!MLDSA65ExternalBackendBridgeReady\(\)\)", "Missing external-backend adapter readiness gate")
        self.assert_match(mldsa_backend_native, r"MLDSA65WrappedSigView wrapped_sig_view;", "Missing external-backend adapter wrapped-signature view parse state")
        self.assert_match(mldsa_backend_native, r"MLDSA65PubKeyView pubkey_view;", "Missing external-backend adapter pubkey view parse state")
        self.assert_match(mldsa_backend_native, r"std::array<unsigned char, 32> ComputeExternalBackendPrehashedSighash\(const CScript& scriptCode,", "Missing external-backend prehashed sighash helper")
        self.assert_match(mldsa_backend_native, r"hasher\.Write\(MLDSA65_EXTERNAL_BACKEND_PREHASH_DOMAIN_TAG\.data\(\), MLDSA65_EXTERNAL_BACKEND_PREHASH_DOMAIN_TAG\.size\(\)\);", "Missing domain-tag contribution in prehashed sighash helper")
        self.assert_match(mldsa_backend_native, r"hasher\.Write\(scriptCode\.data\(\), scriptCode\.size\(\)\);", "Missing scriptCode contribution in prehashed sighash helper")
        self.assert_match(mldsa_backend_native, r"hasher\.Write\(&sighash_type, 1\);", "Missing sighash type contribution in prehashed sighash helper")
        self.assert_match(mldsa_backend_native, r"MLDSA65ExternalBackendRequest request\{", "Missing external-backend canonical request construction")
        self.assert_match(mldsa_backend_native, r"MLDSA65_EXTERNAL_BACKEND_REQUEST_VERSION,", "Missing external-backend request version assignment")
        self.assert_match(mldsa_backend_native, r"MLDSA65_EXTERNAL_BACKEND_CAPABILITIES_BASELINE,", "Missing external-backend request capability assignment")
        self.assert_match(mldsa_backend_native, r"MLDSA65_EXTERNAL_BACKEND_CAPABILITY_PROFILE_BASELINE_V1,", "Missing external-backend request capability-profile assignment")
        self.assert_match(mldsa_backend_native, r"MLDSA65_EXTERNAL_BACKEND_REQUEST_MAGIC,", "Missing external-backend request integrity magic assignment")
        self.assert_match(mldsa_backend_native, r"MLDSA65_EXTERNAL_BACKEND_REQUEST_SHAPE_HASH,", "Missing external-backend request integrity shape-hash assignment")
        self.assert_match(mldsa_backend_native, r"MLDSA65_EXTERNAL_BACKEND_INTERFACE_ID,", "Missing external-backend request interface ID assignment")
        self.assert_match(mldsa_backend_native, r"MLDSA65_EXTERNAL_BACKEND_PREHASH_DOMAIN_TAG,", "Missing external-backend request domain-tag assignment")
        self.assert_match(mldsa_backend_native, r"ComputeExternalBackendPrehashedSighash\(scriptCode, wrapped_sig_view\.sighash_type\),", "Missing external-backend prehashed sighash request assignment")
        self.assert_match(mldsa_backend_native, r"if \(g_mldsa65_external_backend_request_observer != nullptr\)", "Missing external-backend request observer gate")
        self.assert_match(mldsa_backend_native, r"g_mldsa65_external_backend_request_observer\(request\);", "Missing external-backend request observer dispatch")
        self.assert_match(mldsa_backend_native, r"if \(request\.request_content_digest32 != ComputeMLDSA65ExternalBackendRequestContentDigest\(request\)\)", "Missing external-backend post-observer request immutability guard")
        self.assert_match(mldsa_backend_native, r"if \(g_mldsa65_external_backend_result_code_verifier != nullptr\)", "Missing external-backend result-code verifier gate")
        self.assert_match(mldsa_backend_native, r"return TranslateMLDSA65ExternalBackendResultCode\(g_mldsa65_external_backend_result_code_verifier\(request\)\);", "Missing external-backend result-code translation dispatch")
        self.assert_match(mldsa_backend_native, r"g_mldsa65_external_backend_request_observer\(request\);(?:.|\n)*?if \(g_mldsa65_external_backend_result_code_verifier != nullptr\)\s*\{\s*\n\s*return TranslateMLDSA65ExternalBackendResultCode\(g_mldsa65_external_backend_result_code_verifier\(request\)\);\s*\}\s*\n\s*if \(g_mldsa65_external_backend_verifier != nullptr\)\s*\{", "Missing external-backend callback-order contract (observer -> result-code verifier -> verifier)")
        self.assert_match(mldsa_backend_native, r"if \(!ParseMLDSA65WrappedSignature\(wrapped_sig, &wrapped_sig_view\)\)", "Missing external-backend adapter wrapped-signature parse gate")
        self.assert_match(mldsa_backend_native, r"if \(!ParseMLDSA65PubKey\(vchPubKey, &pubkey_view\)\)", "Missing external-backend adapter pubkey parse gate")
        self.assert_match(mldsa_backend_native, r"if \(scriptCode\.empty\(\)\)", "Missing external-backend adapter script non-empty gate")
        self.assert_match(mldsa_backend_native, r"if \(!ParseMLDSA65WrappedSignature\(wrapped_sig, &wrapped_sig_view\)\)\s*\{\s*\n\s*return MLDSA65BackendAdapterResult::REJECTED;\s*\}\s*\n\s*MLDSA65PubKeyView pubkey_view;\s*\n\s*if \(!ParseMLDSA65PubKey\(vchPubKey, &pubkey_view\)\)\s*\{\s*\n\s*return MLDSA65BackendAdapterResult::REJECTED;\s*\}\s*\n\s*if \(scriptCode\.empty\(\)\)\s*\{\s*\n\s*return MLDSA65BackendAdapterResult::REJECTED;\s*\}", "Missing external-backend error-priority contract (wrapped-sig parse -> pubkey parse -> script non-empty)")
        self.assert_match(mldsa_backend_native, r"if \(!MLDSA65ExternalBackendRequestSizesSupported\(", "Missing external-backend adapter request-size gate")
        self.assert_match(mldsa_backend_native, r"if \(!MLDSA65ExternalBackendRequestPointersSupported\(request\)\)", "Missing external-backend adapter request-pointer gate")
        self.assert_match(mldsa_backend_native, r"return MLDSA65BackendAdapterResult::REJECTED;", "Missing external-backend adapter rejected mapping")
        self.assert_match(mldsa_backend_native, r"return MLDSA65BackendAdapterResult::UNAVAILABLE;", "Missing external-backend bridge unavailable fallback")
        self.assert_match(mldsa_backend_native, r"return \{nullptr, nullptr\};", "Missing default native binding empty contract")
        self.assert_match(top_cmake_text, r"option\(ENABLE_MLDSA65_NATIVE_BACKEND\s+\"Enable native ML-DSA-65 backend provider integration\.\"\s+OFF\)", "Missing top-level native ML-DSA backend CMake option")
        self.assert_match(top_cmake_text, r"option\(ENABLE_MLDSA65_EXTERNAL_BACKEND_SCAFFOLD\s+\"Enable ML-DSA-65 external backend integration scaffold \(no verification behavior change\)\.\"\s+OFF\)", "Missing external-backend scaffold CMake option")
        self.assert_match(top_cmake_text, r"set\(MLDSA65_EXTERNAL_BACKEND_HEADER\s+\"\"\s+CACHE STRING\s+\"Optional external ML-DSA-65 backend header to probe when scaffold is enabled\.\"\)", "Missing external-backend header probe cache variable")
        self.assert_match(top_cmake_text, r"set\(MLDSA65_EXTERNAL_BACKEND_LIBRARY\s+\"\"\s+CACHE STRING\s+\"Optional external ML-DSA-65 backend library to probe/link for real verify API dispatch\.\"\)", "Missing external-backend library probe cache variable")
        self.assert_match(top_cmake_text, r"target_compile_definitions\(core_interface INTERFACE ENABLE_MLDSA65_NATIVE_BACKEND\)", "Missing native ML-DSA backend compile-definition wiring")
        self.assert_match(top_cmake_text, r"target_compile_definitions\(core_interface INTERFACE ENABLE_MLDSA65_EXTERNAL_BACKEND_SCAFFOLD\)", "Missing external-backend scaffold compile-definition wiring")
        self.assert_match(top_cmake_text, r"check_include_file_cxx\(\"\$\{MLDSA65_EXTERNAL_BACKEND_HEADER\}\" HAVE_MLDSA65_EXTERNAL_BACKEND_HEADER\)", "Missing external-backend header probe check")
        self.assert_match(top_cmake_text, r"target_compile_definitions\(core_interface INTERFACE HAVE_MLDSA65_EXTERNAL_BACKEND_HEADER\)", "Missing external-backend header-detected compile-definition wiring")
        self.assert_match(top_cmake_text, r"HAVE_MLDSA65_EXTERNAL_BACKEND_VERIFY_API", "Missing external verify API declaration probe wiring")
        self.assert_match(top_cmake_text, r"HAVE_MLDSA65_EXTERNAL_BACKEND_VERIFY_LINK", "Missing external verify API link probe wiring")

        self.log.info("Checking network hard-fork policy height contract")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::MAIN;[\s\S]*?consensus\.maxReorgDepth = 10;\s*consensus\.fjarPolicyHardForkHeight = 118000;", "Mainnet hard-fork policy height must remain 118000")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::MAIN;[\s\S]*?consensus\.fjarPolicyCheckpointHeight = 117800;", "Mainnet checkpoint policy height must remain 117800")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::TESTNET;[\s\S]*?consensus\.maxReorgDepth = 10;\s*consensus\.fjarPolicyHardForkHeight = 118000;", "Testnet hard-fork policy height must mirror mainnet")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::TESTNET;[\s\S]*?consensus\.fjarPolicyCheckpointHeight = 117800;", "Testnet checkpoint policy height must mirror mainnet")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::TESTNET4;[\s\S]*?consensus\.maxReorgDepth = 10;\s*consensus\.fjarPolicyHardForkHeight = 0;", "Testnet4 hard-fork policy height must remain active from height 0")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::TESTNET4;[\s\S]*?consensus\.fjarPolicyCheckpointHeight = 0;", "Testnet4 checkpoint policy height must remain active from height 0")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::REGTEST;[\s\S]*?consensus\.maxReorgDepth = 0;\s*consensus\.fjarPolicyHardForkHeight = 0;", "Regtest hard-fork policy height must remain active from height 0")
        self.assert_match(chainparams_kernel_text, r"m_chain_type = ChainType::REGTEST;[\s\S]*?consensus\.fjarPolicyCheckpointHeight = 0;", "Regtest checkpoint policy height must remain active from height 0")
        self.assert_match(mldsa_backend_impl, r"struct BackendVector", "Missing backend vector table entry type")
        self.assert_match(mldsa_backend_impl, r"const std::array<BackendVector,\s*2> KNOWN_GOOD_BACKEND_VECTORS", "Missing known-good backend vector table")
        self.assert_match(mldsa_backend_impl, r"bool MatchesBackendVector\(const std::vector<unsigned char>& wrapped_sig,", "Missing backend vector matcher helper")
        self.assert_match(mldsa_backend_impl, r"for \(const BackendVector& vector : KNOWN_GOOD_BACKEND_VECTORS\)", "Missing backend vector table iteration")
        self.assert_match(
            mldsa_backend_impl,
            r"MLDSA65BackendAdapterResult::VERIFIED|==\s*MLDSA65BackendAdapterResult::VERIFIED",
            "Backend adapter must expose deterministic success path",
        )
        self.assert_match(
            mldsa_backend,
            r"const MLDSA65BackendAdapterResult adapter_result =\s*VerifyMLDSA65BackendAdapterResult\(wrapped_sig, vchPubKey, scriptCode\);",
            "Missing backend adapter invocation in verify flow",
        )
        self.assert_match(mldsa_backend, r"bool IsLowSValue\(const std::vector<unsigned char>& wrapped_sig, size_t s_offset, size_t s_len\)", "Missing low-S helper in ML-DSA backend")
        self.assert_match(mldsa_backend, r"const bool s_is_low = IsLowSValue\(wrapped_sig, s_offset, s_len\);", "Missing low-S derivation in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(!s_is_low\)", "Missing low-S policy guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(r_first & 0x80\)", "Missing DER negative-R guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(s_first & 0x80\)", "Missing DER negative-S guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"const bool r_is_minimally_encoded = !\(r_len > 1 && r_first == 0x00 && !\(wrapped_sig\[r_offset \+ 1\] & 0x80\)\);", "Missing DER R minimal-encoding derivation in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(!r_is_minimally_encoded\)", "Missing DER redundant-leading-zero R guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"const bool s_is_minimally_encoded = !\(s_len > 1 && s_first == 0x00 && !\(wrapped_sig\[s_offset \+ 1\] & 0x80\)\);", "Missing DER S minimal-encoding derivation in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(!s_is_minimally_encoded\)", "Missing DER redundant-leading-zero S guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(wrapped_sig\.back\(\) == 0x00\)", "Missing non-zero hashtype guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(vchPubKey\.empty\(\)\)", "Missing pubkey empty guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(vchPubKey\.size\(\) > MAX_PUBKEY_SIZE\)", "Missing pubkey oversize guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"const bool is_compressed = \(vchPubKey\.size\(\) == 33\) && \(pubkey_prefix == 0x02 \|\| pubkey_prefix == 0x03\);", "Missing compressed pubkey shape guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"const bool is_uncompressed = \(vchPubKey\.size\(\) == 65\) && \(pubkey_prefix == 0x04\);", "Missing uncompressed pubkey shape guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(!is_compressed && !is_uncompressed\)", "Missing pubkey-format validation guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"if \(out_view != nullptr\)", "Missing parse output-view writeback in ML-DSA backend")
        self.assert_match(mldsa_backend, r"out_view->der_sig_offset = 0;", "Missing wrapped-signature DER offset assignment")
        self.assert_match(mldsa_backend, r"out_view->r_offset = r_offset;", "Missing wrapped-signature R offset assignment")
        self.assert_match(mldsa_backend, r"out_view->r_size = r_len;", "Missing wrapped-signature R size assignment")
        self.assert_match(mldsa_backend, r"out_view->r_is_minimally_encoded = r_is_minimally_encoded;", "Missing wrapped-signature R minimal-encoding assignment")
        self.assert_match(mldsa_backend, r"out_view->s_offset = s_offset;", "Missing wrapped-signature S offset assignment")
        self.assert_match(mldsa_backend, r"out_view->s_size = s_len;", "Missing wrapped-signature S size assignment")
        self.assert_match(mldsa_backend, r"out_view->s_is_minimally_encoded = s_is_minimally_encoded;", "Missing wrapped-signature S minimal-encoding assignment")
        self.assert_match(mldsa_backend, r"out_view->s_is_low = s_is_low;", "Missing wrapped-signature S low-value assignment")
        self.assert_match(mldsa_backend, r"out_view->sighash_offset = der_sig_size;", "Missing wrapped-signature sighash offset assignment")
        self.assert_match(mldsa_backend, r"out_view->payload_offset = 1;", "Missing pubkey payload offset assignment")
        self.assert_match(mldsa_backend, r"out_view->payload_size = vchPubKey\.size\(\) - 1;", "Missing pubkey payload size assignment")
        self.assert_match(mldsa_backend, r"out_view->prefix = pubkey_prefix;", "Missing pubkey prefix assignment")
        self.assert_match(mldsa_backend, r"return ParseMLDSA65WrappedSignature\(wrapped_sig, nullptr\);", "Wrapped-signature structural helper must delegate to parse API")
        self.assert_match(mldsa_backend, r"return ParseMLDSA65PubKeyDetailed\(vchPubKey, out_view, nullptr\);", "Pubkey parse API must delegate to detailed parse API")
        self.assert_match(mldsa_backend, r"return ParseMLDSA65PubKey\(vchPubKey, nullptr\);", "Pubkey structural helper must delegate to parse API")
        self.assert_match(mldsa_backend, r"return VerifyMLDSA65SignatureDetailed\(wrapped_sig, vchPubKey, scriptCode, nullptr\);", "Verify API must delegate to detailed verify API")
        self.assert_match(mldsa_backend, r"void SetMLDSA65BackendVerifierForTesting\(MLDSA65BackendVerifier verifier\)", "Missing ML-DSA backend hook setter")
        self.assert_match(mldsa_backend, r"void ResetMLDSA65BackendVerifierForTesting\(\)", "Missing ML-DSA backend hook resetter")
        self.assert_match(mldsa_backend, r"if \(!IsStructurallyValidMLDSA65WrappedSignature\(wrapped_sig\)\)", "Verify must delegate wrapped signature checks to parser helper")
        self.assert_match(mldsa_backend, r"if \(!IsStructurallyValidMLDSA65PubKey\(vchPubKey\)\)", "Verify must delegate pubkey checks to parser helper")
        self.assert_match(mldsa_backend, r"if \(scriptCode\.empty\(\)\)", "Missing scriptCode non-empty guard in ML-DSA backend")
        self.assert_match(mldsa_backend, r"return false;", "ML-DSA backend placeholder must remain deterministic false")

        self.log.info("Code Quantum runtime contract checks passed")

    def assert_match(self, text: str, pattern: str, message: str):
        if re.search(pattern, text, re.MULTILINE | re.DOTALL) is None:
            raise AssertionError(message)


if __name__ == "__main__":
    CodeQuantumRuntimeContractTest(__file__).main()
