
.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. fjarcode_qt test_fjarcode_qt
clean: FORCE
	$(MAKE) -C .. fjarcode_qt_clean test_fjarcode_qt_clean
check: FORCE
	$(MAKE) -C .. test_fjarcode_qt_check
fjarcode-qt fjarcode-qt.exe: FORCE
	 $(MAKE) -C .. fjarcode_qt
apk: FORCE
	$(MAKE) -C .. fjarcode_qt_apk
